### ISSUE TITLE
Add HDX group list to accepted countries/regions

### ISSUE THREAD

**Issue by mojodna** [OCHA-DAP/hdx-python-api#10]
Per Alex G, we can use the abbreviations from https://data.humdata.org/api/action/group_list?all_fields=true to specify countries. However, since this library is doing ISO3 validation using Geonames, countries / regions e.g. `nepal_earthquake` will be dropped.

**Comment by mcarans** [comment]
HDX Python 1.1.0 on PyPi fixes this. @mojodna  Please confirm and close.

**Comment by mojodna** [comment]
Fantastic!
