### ISSUE TITLE
hdx-python-api 1.4.2 not compatible with CKAN 2.6?

### ISSUE THREAD

**Issue by bdon** [OCHA-DAP/hdx-python-api#12]
demo-data.humdata.org seems like it was changed recently, I'm getting this error: 

HDXError: Failed when trying to read: id={uid}! (POST) - ['https://demo-data.humdata.org/api/action/related_list', 400, u'"Bad request - Action name not known: related_list"']

**Comment by mcarans** [comment]
Ckan 2.6 drops related items which are used for gallery items in HDX. HDX devs have replaced related items with the showcase extension. This change will need to be reflected in the HDX Python library.

**Comment by mcarans** [comment]
HDX Python 2.0.0 released with CKAN 2.6 support. Please let me know if this works for you @bdon.

**Comment by mcarans** [comment]
Note that showcases do not work like gallery items: there can be many datasets in one showcase. Hence showcases are not embedded into datasets like gallery items (related items) were, but should be created through the Showcase class.

HDX Python 2.0.0 is a breaking API change because of the above.

**Comment by bdon** [comment]
@mcarans we may need to change our approach to adding a link to each dataset then. Showcases seem to have a top level list https://data.humdata.org/showcase - this list has a lot of our OSM Exports uploaded objects, which is troublesome. I think we'll just inline the information as text into the description and drop the image link.
