### ISSUE TITLE
dataset 'acled-conflict-data-for-africa-realtime-2016' in the example doesn't return anything

### ISSUE THREAD

**Issue by vanitech** [OCHA-DAP/hdx-python-api#17]
I was able to run the example at https://github.com/OCHA-DAP/hdx-python-api#a-quick-example by changing to a different dataset 'acled-conflict-data-for-africa-1997-lastyear'

**Comment by mcarans** [comment]
Thanks. I have pushed a change to the README. Please let me know if that works for you and if so, I will close the ticket.

**Comment by mcarans** [comment]
No update so closing
