### ISSUE TITLE
Database link in readme.md does not exist

### ISSUE THREAD

**Issue by MichlF** [OCHA-DAP/hdx-python-api#30]
The database file "ACLED Conflict Data for Africa 1997-2016" used in the usage example in the readme.md does not exist anymore and consequently fails the example code.

**Comment by mcarans** [comment]
@MichlF Thanks for spotting this error. I will look into this.

**Comment by mcarans** [comment]
I have updated the README. Closing.

**Comment by MichlF** [comment]
That fixed it but there's now another/new issue. This method, doesn't exist:
`print(dataset.get_dataset_date())`

I think it should be:
`print(dataset.get_date_of_dataset)`
