### ISSUE TITLE
Add hdx-python-api to conda-forge

### ISSUE THREAD

**Issue by turnerm** [OCHA-DAP/hdx-python-api#38]

**Comment by kynan** [comment]
Dependencies:
* [x] ckanapi >= 4.7
* [x] defopt >= 6.4.0
* [x] email_validator
* [ ] hdx-python-country>=3.4.2 (hdx-python-country#14)
* [x] makefun
* [x] ndg-httpsclient
* [x] pyasn1
* [x] pyOpenSSL
* [ ] quantulum3 (conda-forge/staged-recipes#21159)

**Comment by kynan** [comment]
All dependencies are now packaged! Sent conda-forge/staged-recipes#21987

**Comment by kynan** [comment]
Done! The [package is now live](https://anaconda.org/conda-forge/hdx-python-api) @turnerm @mcarans, however I can't seem to mark this issue fixed.

**Comment by mcarans** [comment]
Closing
