### ISSUE TITLE
Upload package to PyPI (bumping version numbers as necessary)

### ISSUE THREAD

**Issue by bdon** [OCHA-DAP/hdx-python-api#4]
I also realized we should add any new dependencies, namely `six` to the requirements in `setup.py`

**Comment by mcarans** [comment]
Added six to setup.py and converted README.md to README.rst as PyPI needs rst

**Comment by mcarans** [comment]
Going to use twine and automate this as per https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

**Comment by mcarans** [comment]
Done
