### ISSUE TITLE
API field definitions

### ISSUE THREAD

**Issue by dividor** [OCHA-DAP/hdx-python-api#56]
Hi HDX Team!

I have a few general questions please about fields returned by this amazing API ...

1. There are lots of fields in the dataset and resource records returned by the API. I've looked through [the documentation](https://hdx-python-api.readthedocs.io/en/latest/api-documentation/dataset/?#dataset-objects) but I cannot seem to find definitions of the fields on these records. For example, if I search for 'total_res_downloads' I can't seem to find anything. There are lots of super useful fields we could perhaps use, but I wondered if these fields might have definitions somewhere I could review?

2. For download and page view metrics, I see fields on the 'dataset' record, but not on the 'resource' (file) records. It would be great to know which resources are being downloaded as an indication of their popularity. Sorry if I've asked this before, but is it possible to identify via the API any metrics on how often a resources was downloaded in, say, the last 14 days?

3. I would like to identify recently changed data on HDX. I see last_modified on the resource and dataset records, will this field change on dataset if one of its resources is updated?

Thanks so much.

**Comment by mcarans** [comment]
1. Important fields that are exposed in the UI are documented here: https://centre.humdata.org/providing-metadata-for-your-datasets-on-hdx/. For any where it isn't clear which API fields they correspond to, then please let me know. `total_res_downloads` is the total number of resource downloads. If there are any other fields you'd like info on, please let me know.

2. The API only has the fields you can see in the dataset. For more detailed download information, please contact the HDX team directly by email: hdx@un.org

3. You are right. Note that `last_modified` changes when data is updated. You can use `metadata_modified` for when the metadata changes.

**Comment by dividor** [comment]
Thanks!
