### ISSUE TITLE
Can't execute code from the docs: No module named 'hdx.api'; 'hdx' is not a package

### ISSUE THREAD

**Issue by zxqfd555-pw** [OCHA-DAP/hdx-python-api#73]
Hello!

I am trying to get access to HDX Datasets with the Python library. I am following [this tutorial](https://hdx-python-api.readthedocs.io/en/latest/). I skipped the part with the API key, in the beginning, since I only wanted to read a dataset.

To set the stage, I create a virtual environment and install `hdx-python-api` with `pip`:

```bash
virtualenv venv
. venv/bin/activate
pip install hdx-python-api
```

These preparations finish successfully. But then I try to run the Python code from the next sections. So I launch `python` and enter the very first line from item 7. in the doc:

```python
from hdx.utilities.easy_logging import setup_logging
```

And it ends up with an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sergey/IoT-Pathway/experimental/sergey/mercy-corps/hdx.py", line 1, in <module>
    from hdx.api.configuration import Configuration
ModuleNotFoundError: No module named 'hdx.api'; 'hdx' is not a package
```

Could you please clarify how can I avoid it and download a dataset? The Python version is 3.11.9.

**Comment by mcarans** [comment]
@zxqfd555-pw This may be because your filename hdx.py matches the module name in the library. Please can you try changing your filename and let me know if that helps.

**Comment by zxqfd555-pw** [comment]
Indeed it was connected with the files test script with the same name present in my test folder.
Thank you for your fast reply and sorry for the false alert!
