### ISSUE TITLE
Unable to remove country locations

### ISSUE THREAD

**Issue by mojodna** [OCHA-DAP/hdx-python-api#9]
`dataset.add_country_locations` and `dataset.add_country_location` both allow countries to be _added_ to a dataset on HDX but don't clear out the existing set of countries (even if `dataset['groups'] = []` first).

**Comment by mcarans** [comment]
@mojodna This has been fixed in 1.0.6 release of library on PyPI. Please confirm it is ok for you and close this ticket if so.

**Comment by mojodna** [comment]
Fantastic, thanks!!
